version: 1.0.{build}

os:
  - Visual Studio 2015
platform: 
- Win32

install:
  - cd win
  - git clone https://github.com/HOST-Oman/raqm-dependencies.git
  - cd raqm-dependencies
  - mkdir build
  - cd build
  - cmake ..
  - cmake --build . --config Debug 
  - cd ../../../
  
build:

build_script:
  # build the library 
  - cmake -DUNIT_TEST=1 -DWANT_DEBUG=1 -DSTATIC_LIB=1 -DRAQM_DEPENS_DIR:PATH="win/raqm-dependencies/build/dependencies"
  # build the library for Release and Debug
  - cmake --build . --config Debug 
  - ctest -C "Debug"
  
after_build:
  # Install only release 
  #- cmd: cmake --build C:\dev\lib-template-cmake\build --config Release --target INSTALL

# For some reason, tests are not working. Debug this and enable them again
# test_script:
#   - cmd: ctest -C Release -VV
