sudo: required # needed for trusty beta
dist: trusty   # needed for HarfBuzz

os:
  - linux
  - osx

language: c

compiler:
  - gcc
  - clang

matrix:
  allow_failures:
    - os: osx
      compiler: gcc

before_install:
  - if [ "$TRAVIS_OS_NAME" == "linux" ]; then
      sudo add-apt-repository ppa:as-bahanta/raqm -y;
      sudo apt-get update -qq;
      sudo apt-get install -y cmake libfreetype6-dev libharfbuzz-dev libfribidi-dev libglib2.0-dev gtk-doc-tools;
    fi
  - if [ "$TRAVIS_OS_NAME" == "osx" ]; then
      brew update;
      brew uninstall libtool && brew install libtool;
      brew install freetype harfbuzz fribidi glib gtk-doc;
      export XML_CATALOG_FILES="/usr/local/etc/xml/catalog";
    fi;
  - if [ "${TRAVIS_OS_NAME}" == "osx" -a "${CC}" == "gcc" ]; then export CC=gcc-4.8; fi

script:
  - cmake -DUNIT_TEST=1 -DWANT_DEBUG=1 -DENABLE_GTK_DOC=1
  - make
  - make test
  - make docs

after_success:
  - if [ "$TRAVIS_OS_NAME" == "linux" -a "$CC" == "gcc" -a "$TRAVIS_SECURE_ENV_VARS" == "true" ];
      then bash .ci/deploy-docs.sh;
    fi

notifications:
  email:
    recipients:
      - host-oman@googlegroups.com
